In [1]:
import geopandas as gpd
import pyogrio as ogr
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import LineString, MultiLineString, Point, Polygon
import pandas as pd
import requests
import networkx as nx
import osmnx as ox
import h3
import libpysal as lps

In [2]:
csv_data = pd.read_csv("./Primary_Land_Use_Tax_Lot_Output__PLUTO__20240725.csv")

csv_data.head()

C:\Users\zheng\AppData\Local\Temp\ipykernel_18300\2320791634.py:1: DtypeWarning: Columns (17,18,20,21,22,24,25,52,61,62,97) have mixed types. Specify dtype option on import or set low_memory=False.
  csv_data = pd.read_csv("./Primary_Land_Use_Tax_Lot_Output__PLUTO__20240725.csv")

,borough,block,lot,community board,census tract 2010,cb2010,schooldist,council district,postcode,firecomp,...,landmkdate,basempdate,masdate,polidate,edesigdate,geom,dcpedited,notes,bct2020,bctcb2020
0,SI,490,45,501.0,21.0,2019.0,31.0,49.0,10304.0,L077,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5002100.0,5.002100e+10
1,SI,2965,12,501.0,36.0,1000.0,31.0,49.0,10305.0,E153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5003600.0,5.003600e+10
2,SI,2965,110,501.0,36.0,1000.0,31.0,49.0,10305.0,E153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5003600.0,5.003600e+10
3,SI,2965,11,501.0,36.0,1000.0,31.0,49.0,10305.0,E153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5003600.0,5.003600e+10
4,SI,2965,20,501.0,36.0,1000.0,31.0,49.0,10305.0,E153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5003600.0,5.003600e+10